# @package _global_

# Hopular hyperparameter optimization with Optuna:
# python train.py -m hparams_search=hopular_binding_site_optuna experiment=binding_site model=hopular_binding_site

defaults:
  - override /hydra/sweeper: optuna

# choose metric which will be optimized by Optuna
optimized_metric: "val/loss"

hydra:
  mode: MULTIRUN # mandatory mode for optimization
  sweeper:
    _target_: hydra._internal.utils.create_config_search_path
    search_space:
      model.optimizer.lr:
        type: float
        low: 0.0001
        high: 0.01
        log: true
      model.hidden_dim:
        type: categorical
        choices: [64, 128, 256, 512]
      model.hopfield_dim:
        type: categorical
        choices: [32, 64, 128]
      model.heads:
        type: categorical
        choices: [2, 4, 8]
      model.dropout:
        type: float
        low: 0.0
        high: 0.3
      model.layers:
        type: int
        low: 2
        high: 6
      model.pattern_dim:
        type: categorical
        choices: [16, 32, 64]
      model.update_steps:
        type: int
        low: 1
        high: 3
      model.polynomial_degree:
        type: int
        low: 2
        high: 4
      data.batch_size:
        type: categorical
        choices: [32, 64, 128]
      data.sampling_strategy:
        type: categorical
        choices: ["none", "oversample", "undersample", "combined"]
    direction: minimize
    n_trials: 100
    n_jobs: 1

    experiment: binding_site
    model: hopular_binding_site
