# Default configuration for the enhanced post-processing pipeline
checkpoint_paths:
  - ../../logs/fusion_transformer_aggressive_oct17/runs/2025-10-23_blend_sweep/selective_swa_epoch09_12.ckpt
h5_file: ../../data/h5/all_train_transformer_v2_optimized.h5
output_dir: ../../post_processing_results
protein_ids: null

enhanced:
  create_pymol: true
  create_individual_folders: true
  generate_summary: true
  save_raw_predictions: true
  save_true_pockets: true
  max_pockets: 5
  adaptive_percentiles: [95, 90, 85, 80]
  fallback_threshold: 0.3
