# ESM-augmented PockNet model configuration

_target_: src.models.pocknet_esm_binding_site_module.PockNetESMBindingSiteModule

# Architecture parameters
tabular_dim: 42      # Dimension of tabular features
esm_dim: 2560        # Dimension of ESM embeddings (ESM-2 default)
output_dim: 1        # Output dimension (binary classification)

# TabNet architecture parameters
n_steps: 3           # Number of decision steps
n_d: 32              # Dimension of decision features
n_a: 32              # Dimension of attention features
n_shared: 2          # Number of shared layers in feature transformer
n_independent: 2     # Number of independent layers per step
gamma: 1.3           # Coefficient for attention regularization
epsilon: 1e-15       # Small constant for numerical stability
dropout: 0.2         # Dropout rate

# ESM-specific parameters
esm_projection_dim: 128    # Dimension to project ESM embeddings to
fusion_strategy: "concatenate"  # Options: "concatenate", "attention", "gated"

# Metrics
use_iou_metric: true

# Optimizer configuration
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.003
  weight_decay: 1e-5

# Learning rate scheduler
scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: "min"
  factor: 0.5
  patience: 10
  verbose: true
