# @package _global_

defaults:
  - default

_target_: src.models.xgboost_binding_site_module.XGBoostBindingSiteModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

# XGBoost hyperparameters
learning_rate: 0.1
max_depth: 6
n_estimators: 100
subsample: 0.8
colsample_bytree: 0.8
gamma: 0
reg_alpha: 0
reg_lambda: 1
use_iou_metric: true
