# Default configuration mirroring P2Rank params.groovy
rf_trees: 200  # number of trees
rf_depth: 0    # 0 means unlimited depth
rf_features: 0 
rf_threads: 0  # 0 means use all available
rf_bagsize: 100 # percentage of samples for each tree
seed: 1234567
train_csv: ../output_chen11/vectorsTrain.csv
finetune_csv: ../output_train/finetune.csv
test_csv: ../output_holo4k/vectorsTrain.csv
features_file: ../features.txt

# Additional options for imbalanced data
class_weight: "balanced"  # "balanced", "balanced_subsample", or null for no weighting
validation_size: 0.2  # Fraction of training data to use for validation
finetune_trees: 200  # Number of additional trees to add during finetuning (0 means same as rf_trees)