# @package _global_

defaults:
  - _self_
  - data: h5_transformer_aggregation
  - model: esm_tabular_transformer
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
