# @package _global_

# This config is for evaluating on bu48 dataset with ESM2 embeddings

defaults:
  - _self_
  - paths: default
  - trainer: gpu
  - model: tabnet_binding_site
  - data: binding_site_esm  # Use our new ESM data module
  - callbacks: default
  - logger: wandb
  - debug: default
  - experiment: bu48_eval
  - hydra: default

# Override any default configurations here
seed: 42
name: tabnet_bu48_esm_evaluation
trainer:
  max_epochs: 1

data:
  batch_size: 1024
  sampling_strategy: "combined"
  embedding_type: "mean"
  eval_dataset: "bu48"

# Additional configuration for the run
hydra:
  job:
    name: ${name}
